version: '3.9'

services:
  nginx:
    image: nginx:latest
    ports:
      - '8087:80'
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    links:
      - php-fpm

  php-fpm:
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
